name: Deploy Vue App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ secrets.NAME }}"
          git config --global user.email "{{ secrets.EMAIL }}"
          bun run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
